#!/bin/sh
if [ -f /etc/default/raspberrypi-kernel ]; then
  . /etc/default/raspberrypi-kernel
  INITRD=${INITRD:-"No"}
  export INITRD
  RPI_INITRD=${RPI_INITRD:-"No"}
  export RPI_INITRD
fi
if [ -d "/etc/kernel/header_postinst.d" ]; then
  run-parts -v --verbose --exit-on-error --arg=6.1.21+ /etc/kernel/header_postinst.d
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v7+ /etc/kernel/header_postinst.d
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v7l+ /etc/kernel/header_postinst.d
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v8+ /etc/kernel/header_postinst.d
fi

if [ -d "/etc/kernel/header_postinst.d/6.1.21+" ]; then
  run-parts -v --verbose --exit-on-error --arg=6.1.21+ /etc/kernel/header_postinst.d/6.1.21+
fi

if [ -d "/etc/kernel/header_postinst.d/6.1.21-v7+" ]; then
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v7+ /etc/kernel/header_postinst.d/6.1.21-v7+
fi
if [ -d "/etc/kernel/header_postinst.d/6.1.21-v7l+" ]; then
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v7l+ /etc/kernel/header_postinst.d/6.1.21-v7l+
fi
if [ -d "/etc/kernel/header_postinst.d/6.1.21-v8+" ]; then
  run-parts -v --verbose --exit-on-error --arg=6.1.21-v8+ /etc/kernel/header_postinst.d/6.1.21-v8+
fi
#DEBHELPER#
