#!/bin/sh
# vim:ts=2:sw=2:et

set -e

is_arm_system() {
  # Check to see if the host is running an arm-based system
  # (i.e. whether the raspi-firmware package is useful)
  DPKG_ARCH=$(dpkg --print-architecture)
  case "$DPKG_ARCH" in
    arm64|armel|armhf)
      return 0;;
    *)
      return 1;;
  esac
}

case "$1" in
  configure)
    if ! is_arm_system ; then
      # Not running on an arm-based system, skip the postinst
      exit 0
    fi

    if ischroot ; then
      true # chroot detected - skip mount point check
    elif test -e /usr/bin/systemd-detect-virt && systemd-detect-virt -q ; then
      true # virtualization detected - skip mount point check
    elif [ "$(stat -f -c %T /boot/firmware)" = "nfs" ]; then
      true
    elif ! mountpoint -q /boot/firmware; then
      echo "Error: missing /boot/firmware, did you forget to mount it?" >&2
      exit 1
    fi

    # Ensure the target directory exists. See https://bugs.debian.org/887062
    mkdir -p /boot/firmware

    cp -r /usr/lib/raspi-firmware/* /boot/firmware/
    sync -f /boot/firmware || true

    # Manually trigger the kernel postinst hook when raspi-firmware is first
    # installed (or upgraded), as the kernel package might already be installed
    # (or not upgraded) and hence the hook would not get triggered otherwise.
    if hash linux-version 2> /dev/null; then
      linux-version list --paths | while read -r line; do
        # shellcheck disable=SC2086
        DEB_MAINT_PARAMS="configure" /etc/kernel/postinst.d/z50-raspi-firmware $line
      done
    fi

    ;;
esac

#DEBHELPER#

exit 0
